/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ArcadeGameService } from "../arcadeGame.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ArcadeGameCreateInput } from "./ArcadeGameCreateInput";
import { ArcadeGameWhereInput } from "./ArcadeGameWhereInput";
import { ArcadeGameWhereUniqueInput } from "./ArcadeGameWhereUniqueInput";
import { ArcadeGameFindManyArgs } from "./ArcadeGameFindManyArgs";
import { ArcadeGameUpdateInput } from "./ArcadeGameUpdateInput";
import { ArcadeGame } from "./ArcadeGame";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ArcadeGameControllerBase {
  constructor(
    protected readonly service: ArcadeGameService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ArcadeGame",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ArcadeGame })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ArcadeGameCreateInput
  ): Promise<ArcadeGame> {
    return await this.service.create({
      data: data,
      select: {
        commands: true,
        createdAt: true,
        fishDamages: true,
        fishUpdateInterval: true,
        gameBalanceInCents: true,
        gameCode: true,
        gameId: true,
        gameSettings: true,
        id: true,
        payTables: true,
        sceneBullets: true,
        sceneFish: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ArcadeGame",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [ArcadeGame] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ArcadeGameFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<ArcadeGame[]> {
    const args = plainToClass(ArcadeGameFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        commands: true,
        createdAt: true,
        fishDamages: true,
        fishUpdateInterval: true,
        gameBalanceInCents: true,
        gameCode: true,
        gameId: true,
        gameSettings: true,
        id: true,
        payTables: true,
        sceneBullets: true,
        sceneFish: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ArcadeGame",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ArcadeGame })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ArcadeGameWhereUniqueInput
  ): Promise<ArcadeGame | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        commands: true,
        createdAt: true,
        fishDamages: true,
        fishUpdateInterval: true,
        gameBalanceInCents: true,
        gameCode: true,
        gameId: true,
        gameSettings: true,
        id: true,
        payTables: true,
        sceneBullets: true,
        sceneFish: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ArcadeGame",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ArcadeGame })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ArcadeGameWhereUniqueInput,
    @common.Body() data: ArcadeGameUpdateInput
  ): Promise<ArcadeGame | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          commands: true,
          createdAt: true,
          fishDamages: true,
          fishUpdateInterval: true,
          gameBalanceInCents: true,
          gameCode: true,
          gameId: true,
          gameSettings: true,
          id: true,
          payTables: true,
          sceneBullets: true,
          sceneFish: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "ArcadeGame",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ArcadeGame })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ArcadeGameWhereUniqueInput
  ): Promise<ArcadeGame | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          commands: true,
          createdAt: true,
          fishDamages: true,
          fishUpdateInterval: true,
          gameBalanceInCents: true,
          gameCode: true,
          gameId: true,
          gameSettings: true,
          id: true,
          payTables: true,
          sceneBullets: true,
          sceneFish: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
