/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { FriendRelationshipListRelationFilter } from "../../friendRelationship/base/FriendRelationshipListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { PrivateMessageListRelationFilter } from "../../privateMessage/base/PrivateMessageListRelationFilter";
import { RoomMessageListRelationFilter } from "../../roomMessage/base/RoomMessageListRelationFilter";
import { EnumUserStatus } from "./EnumUserStatus";
@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => FriendRelationshipListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FriendRelationshipListRelationFilter)
  @IsOptional()
  @Field(() => FriendRelationshipListRelationFilter, {
    nullable: true,
  })
  friendRelationships?: FriendRelationshipListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => FriendRelationshipListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FriendRelationshipListRelationFilter)
  @IsOptional()
  @Field(() => FriendRelationshipListRelationFilter, {
    nullable: true,
  })
  invites?: FriendRelationshipListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lastName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PrivateMessageListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PrivateMessageListRelationFilter)
  @IsOptional()
  @Field(() => PrivateMessageListRelationFilter, {
    nullable: true,
  })
  privateMessages?: PrivateMessageListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PrivateMessageListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PrivateMessageListRelationFilter)
  @IsOptional()
  @Field(() => PrivateMessageListRelationFilter, {
    nullable: true,
  })
  receivedMessges?: PrivateMessageListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => RoomMessageListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RoomMessageListRelationFilter)
  @IsOptional()
  @Field(() => RoomMessageListRelationFilter, {
    nullable: true,
  })
  roomMessages?: RoomMessageListRelationFilter;

  @ApiProperty({
    required: false,
    enum: EnumUserStatus,
  })
  @IsEnum(EnumUserStatus)
  @IsOptional()
  @Field(() => EnumUserStatus, {
    nullable: true,
  })
  status?: "Online" | "Offline" | "Busy";

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;
}
export { UserWhereInput };
